### ISSUE TITLE
Not an issue, but a request....

### ISSUE THREAD

**Issue by Gozania** [fmaranhao/SonicPadMultipleUSBCameras#1]
First and foremost, TY for doing this!  I dont want to go through the hassle of flashing the debian build for the sonic pad and this your solution is perfect for my needs.   You mentioned Obico,  I have had a subscription since they were spaghetti detective & love their service.  Could you please do an walkthrough to install obico onto our sonic pads?  Would be great if you included steps for multiple printers if you could.

**Comment by fmaranhao** [comment]
Hi, I am pretty sure I linked to the page I used to install Obico. That was actually what triggered me into doing the Multiple USB camera thing... Just follow this page and you should be good:
https://github.com/wavezcs/SonicPadObico

Btw, I have moved to the CSP-Debian since its inception. And it has been working great for me for months! It pretty much unlocks the whole SonicPad's potential.

**Comment by Gozania** [comment]
TY for the reply!  Glad to know that the Debian build is stable.  The install is a bit above my skill level, have a few friends that may be up for the task!   Ty again! From: Fred MaranhaoSent: Thursday, October 5, 2023 7:50 PMTo: fmaranhao/SonicPadMultipleUSBCamerasCc: Gozania; AuthorSubject: Re: [fmaranhao/SonicPadMultipleUSBCameras] Not an issue, but a request.... (Issue #1) Hi, I am pretty sure I linked to the page I used to install Obico. That was actually what triggered me into doing the Multiple USB camera thing... Just follow this page and you should be good:https://github.com/wavezcs/SonicPadObicoBtw, I have moved to the CSP-Debian since its inception. And it has been working great for me for months! It pretty much unlocks the whole SonicPad's potential.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
